import Head from "next/head";
import Image from "next/image";

//Components
import Header from '../components/Header'
import Hero from '../components/Hero/Hero'
import Grid from '../components/Grid/Grid'
import Card from '../components/Card/Card'
import Spinner from '../components/Spinner/Spinner'
import { NextPage } from "next";


const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Movie App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="relative h-screen overflow-y-scroll">
        <Header />
        <Hero />
        <Grid />
        <Card />
        <Spinner />
        
        <p>RMDB</p>
      </main>

      <footer></footer>
    </div>
  );
}

export default Home;