import Head from "next/head";
import Image from "next/image";
// import styles from "../styles/Home.module.css";
import project1 from "../assets/images/picture1.jpg";
import project2 from "../assets/images/picture2.jpg";
import project3 from "../assets/images/picture3.jpg";
import project4 from "../assets/images/picture4.jpg";
import project5 from "../assets/images/picture5.jpg";

// Import Swiper React components
import { Swiper, SwiperSlide } from "swiper/react";

// Import Swiper styles
import "swiper/css";
import "swiper/css/effect-coverflow";
import "swiper/css/pagination";

// import required modules
import { EffectCoverflow, Pagination } from "swiper";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Test Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="flex justify-between mx-16 my-12">
          <p>Everything is easy</p>
          <p>Post a task</p>
          <p>Set your budget or not</p>
          <p>Receive quotes</p>
        </div>
        <div className="flex w-full h-full px-2 App">
          <div className="w-[30%] flex flex-col gap-y-8 pl-[5%]">
            <h1 className="text-3xl mt-28">Explore by <br/>Categories</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum, repellendus.</p>
            <button className="p-4 text-white bg-orange-400 rounded-md">See all Categories</button>
          </div>
          <Swiper
            effect={"coverflow"}
            grabCursor={true}
            centeredSlides={false}
            slidesPerView={3}
            coverflowEffect={{
              rotate: 50,
              stretch: 0,
              depth: 100,
              modifier: 1,
              slideShadows: true,
            }}
            pagination={true}
            modules={[EffectCoverflow, Pagination]}
            className="mySwiper w-[70%] h-[80vh] pt-[10px]"
          >
            <SwiperSlide className="w-full">
              <img
                className="w-[100%] h-[85%] rounded-xl"
                src="https://swiperjs.com/demos/images/nature-1.jpg"
              />
              <p className="text-xl">This is image one</p>
            </SwiperSlide>
            <button className="p-4 bg-orange-400 rounded-full">Drag</button>
            <SwiperSlide className="w-full">
              <img
                className="w-[100%] h-[85%] rounded-xl"
                src="https://swiperjs.com/demos/images/nature-2.jpg"
              />
              <p className="text-xl">This is image two</p>
            </SwiperSlide>
            <SwiperSlide className="w-full">
              <img
                className="w-[100%] h-[85%] rounded-xl"
                src="https://swiperjs.com/demos/images/nature-3.jpg"
              />
            </SwiperSlide>
            <SwiperSlide className="w-full">
              <img
                className="w-[100%] h-[85%] rounded-xl"
                src="https://swiperjs.com/demos/images/nature-4.jpg"
              />
            </SwiperSlide>
            <SwiperSlide className="w-full">
              <img
                className="w-[100%] h-[85%] rounded-xl"
                src="https://swiperjs.com/demos/images/nature-5.jpg"
              />
            </SwiperSlide>
            <SwiperSlide className="w-full">
              <img
                className="w-[100%] h-[85%] rounded-xl"
                src="https://swiperjs.com/demos/images/nature-6.jpg"
              />
            </SwiperSlide>
            <SwiperSlide className="w-full">
              <img
                className="w-[100%] h-[85%] rounded-xl"
                src="https://swiperjs.com/demos/images/nature-7.jpg"
              />
            </SwiperSlide>
            <SwiperSlide className="w-full">
              <img
                className="w-[100%] h-[85%] rounded-xl"
                src="https://swiperjs.com/demos/images/nature-8.jpg"
              />
            </SwiperSlide>
            <SwiperSlide className="w-full">
              <img
                className="w-[100%] h-[85%] rounded-xl"
                src="https://swiperjs.com/demos/images/nature-9.jpg"
              />
            </SwiperSlide>
          </Swiper>
        </div>
      </main>

      <footer></footer>
    </div>
  );
}
